#!/usr/bin/env python3
"""
scheduler.py
Time-based task scheduler for the AI Employee system.

Schedules:
  - Every day at 09:00 → invoke linkedin_post_creator skill via Claude CLI
  - Every Monday at 08:00 → generate CEO Briefing in vault/Briefings/
"""

import logging
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path

import schedule

ROOT  = Path(__file__).parent.parent
VAULT = ROOT / "vault" / "AI_Employee_Vault"

# ── Logger ────────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] Scheduler — %(message)s",
)
logger = logging.getLogger("Scheduler")


def run_linkedin_post():
    """Auto-generate a LinkedIn post via the linkedin_post_creator skill."""
    logger.info("Running daily LinkedIn post generation via linkedin_post_creator skill...")
    try:
        result = subprocess.run(
            [
                "claude", "-p",
                "The daily scheduler has triggered. Run the linkedin_post_creator skill to auto-select a topic and create today's LinkedIn post.",
                "--allowedTools", "all",
            ],
            cwd=str(ROOT),
            capture_output=False,
            timeout=300,
            shell=False,
        )
        if result.returncode == 0:
            logger.info("linkedin_post_creator skill completed.")
        else:
            logger.warning(f"linkedin_post_creator skill exited with code {result.returncode}.")
    except Exception as e:
        logger.exception(f"Error running linkedin_post_creator skill: {e}")


def generate_ceo_briefing():
    """Write a Monday morning CEO briefing from vault logs and dashboard."""
    logger.info("Generating Monday CEO Briefing...")
    try:
        briefings_dir = VAULT / "Briefings"
        briefings_dir.mkdir(parents=True, exist_ok=True)

        today = datetime.now().strftime("%Y-%m-%d")
        briefing_path = briefings_dir / f"{today}_Monday_Briefing.md"

        if briefing_path.exists():
            logger.info(f"Briefing already exists for {today}, skipping.")
            return

        # Read dashboard
        dashboard_path = VAULT / "Dashboard.md"
        dashboard_text = ""
        if dashboard_path.exists():
            dashboard_text = dashboard_path.read_text(encoding="utf-8", errors="ignore")

        # Count done tasks
        done_dir = VAULT / "Done"
        done_files = list(done_dir.rglob("*.md")) if done_dir.exists() else []

        # Count pending approvals
        pending_dir = VAULT / "Pending_Approval"
        pending_files = list(pending_dir.rglob("*.md")) if pending_dir.exists() else []

        # Count tasks per category
        email_done    = [f for f in done_files if "email"    in f.parts[-2] or "email"    in f.name.lower()]
        whatsapp_done = [f for f in done_files if "whatsapp" in f.parts[-2] or "whatsapp" in f.name.lower()]
        linkedin_done = [f for f in done_files if "linkedin" in f.parts[-2] or "linkedin" in f.name.lower()]

        now_iso = datetime.now().isoformat()
        now_hm  = datetime.now().strftime("%H:%M")

        content = f"""---
type: ceo_briefing
generated: {now_iso}
week_start: {today}
---

# Monday Morning CEO Briefing — {today}

Generated automatically by AI Employee Scheduler at {now_hm}.

---

## Task Summary

| Category | Completed |
|----------|-----------|
| Email | {len(email_done)} |
| WhatsApp | {len(whatsapp_done)} |
| LinkedIn Posts | {len(linkedin_done)} |
| **Total Done** | **{len(done_files)}** |

**Pending Approval:** {len(pending_files)} item(s) awaiting your review.

---

## Dashboard Snapshot

{dashboard_text[:2000]}

---

## Recommended Actions

1. Review `Pending_Approval/` — {len(pending_files)} item(s) need your decision.
2. Check `Logs/` for any errors or anomalies from the past week.
3. LinkedIn queue: Approve any pending posts in `Pending_Approval/linkedin/`.

---

*This briefing was auto-generated by the AI Employee scheduling system.*
"""

        briefing_path.write_text(content, encoding="utf-8")
        logger.info(f"CEO Briefing written: {briefing_path.name}")

    except Exception as e:
        logger.exception(f"Error generating CEO briefing: {e}")


# ── Schedule definitions ──────────────────────────────────────────────────────

schedule.every().day.at("09:00").do(run_linkedin_post)
schedule.every().monday.at("08:00").do(generate_ceo_briefing)

logger.info("Started.")
logger.info("  - LinkedIn post: daily at 09:00")
logger.info("  - CEO Briefing:  every Monday at 08:00")

# ── Startup catch-up: run missed jobs if not yet done today ──────────────────
_now = datetime.now()
_today_str = _now.strftime("%Y%m%d")  # e.g. 20260325 — matches LINKEDIN_POST_ filenames

# LinkedIn post catch-up: if 09:00 has already passed and no post exists for today
if _now.hour >= 9:
    _linkedin_dirs = [
        VAULT / "Pending_Approval" / "linkedin",
        VAULT / "Approved" / "linkedin",
        VAULT / "Done" / "linkedin",
    ]
    _post_exists_today = any(
        list(d.glob(f"LINKEDIN_POST_{_today_str}*.md"))
        for d in _linkedin_dirs
        if d.exists()
    )
    if not _post_exists_today:
        logger.info("Startup catch-up — 09:00 passed with no LinkedIn post today. Generating now...")
        run_linkedin_post()
    else:
        logger.info("Startup catch-up — LinkedIn post already exists for today. Skipping.")

# CEO Briefing catch-up: Mondays only
if _now.weekday() == 0:  # 0 = Monday
    _today = _now.strftime("%Y-%m-%d")
    _briefing_path = VAULT / "Briefings" / f"{_today}_Monday_Briefing.md"
    if not _briefing_path.exists():
        logger.info("Monday detected on startup — running missed CEO Briefing now.")
        generate_ceo_briefing()

while True:
    try:
        schedule.run_pending()
    except Exception as e:
        logger.exception(f"Unexpected error in scheduler loop: {e}")
    time.sleep(60)
